# Generated by Django 4.1.9 on 2024-05-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashAquaponia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashmodel',
            name='qtdeVendaPeixe',
            field=models.IntegerField(default=0, verbose_name='VendaPeixe'),
            preserve_default=False,
        ),
    ]
